name: .NET Build and Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      TestSettings__TransactionDigest2: ${{ secrets.TEST_TRANSACTION_DIGEST2 }}
      TestSettings__TransactionDigest: ${{ secrets.TEST_TRANSACTION_DIGEST }}
      TestSettings__ObjectId2: ${{ secrets.TEST_OBJECT_ID2 }}
      TestSettings__ObjectId: ${{ secrets.TEST_OBJECT_ID }}
      TestSettings__Address: ${{ secrets.TEST_ADDRESS }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration Release --no-restore -noWarn:NUnit2005
      
    - name: Run tests
      run: dotnet test iota-sdk-tests/iota-sdk-tests.csproj --configuration Release --verbosity normal